[workspace]
members = ["xmplayer", "display", "modplayer-bin", "modplayer-wasm", "modplayer-bindgen", "modplayer-lib"]


#[profile.release]
#lto = true
#panic = 'abort'

# uncomment for termux
#[patch.crates-io]
#termios = { path = "vendor/termios-0.2.2" }
