default-target = "wasm32-unknown-emscripten"

[target.emscripten]
link-args = [
    "-s", "WASM=1",
    "-s", "USE_SDL=2",
    "-s", "FORCE_FILESYSTEM=1",
    "--js-library", "modplayer-emscripten/src/static/library.js",
    "-g4"
]
