[package]
name = "modplayer-wasm"
version = "0.1.0"
authors = ["gilad.benor@gmail.com"]
edition = "2018"


[dependencies]
crossbeam = "0.7"
xmplayer = {path="../xmplayer"}
lazy_static = "1.4.0"

[profile.release]
lto = true
