default-target = "wasm32-unknown-emscripten"

[target.emscripten]
link-args = [
    "-s", "WASM=1",
    "-s", "USE_SDL=2",
    "--embed-file", "/Users/gil-ad/rust/modplayer/modplayer-wasm/src/static/thraddash.mod"
]
